# Generated by Django 3.0.5 on 2020-04-13 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=10)),
                ('tone', models.CharField(max_length=5)),
                ('rhyme', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SM',
            fields=[
                ('sm', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='YM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ym', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=30)),
                ('c1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c1', to='rhyme.Character')),
                ('c2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c2', to='rhyme.Character')),
                ('c3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c3', to='rhyme.Character')),
                ('c4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c4', to='rhyme.Character')),
                ('c5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c5', to='rhyme.Character')),
                ('c6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c6', to='rhyme.Character')),
                ('c7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c7', to='rhyme.Character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='csm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rhyme.SM'),
        ),
        migrations.AddField(
            model_name='character',
            name='cym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rhyme.YM'),
        ),
    ]
