# Generated by Django 3.0.5 on 2020-04-13 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhyme', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='phrase',
            index_together={('c1', 'c2', 'c3', 'c4')},
        ),
    ]
